apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: mongodb
type: Opaque
stringData:
  # MongoDB root password
  password: "<password-here>"
  # MongoDB connection string (optional)
  connectionString.standardSrv: "mongodb://admin:<password-here>@mongodb-svc.mongodb.svc.cluster.local:27017"
