services:
  mongo:
    image: mongodb/mongodb-atlas-local
    container_name: mongo
    restart: unless-stopped
    volumes:
      - ./data/mongo/db:/data/db
    ports:
      - "27017:27017"
    env_file:
      - ./mongo.env
