name: "homelab"

include:
  # services
  - ./services/traefik/compose.yml
  - ./services/redis/compose.yml
  - ./services/mongo/compose.yml
  - ./services/minio/compose.yml

  # apps
  - ./apps/delulu/compose.yml