services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/traefik/certs
      - ./logs:/etc/traefik/log
      - ./users:/etc/traefik/users:ro
      - ./config:/etc/traefik/config:ro
    environment:
      - DOCKER_API_VERSION=1.44
    env_file:
      - ./traefik.env
    labels:
      - "traefik.enable=true"
