global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
  format: json
  filePath: /etc/traefik/log/traefik.log
accesslog:
  format: json
  filePath: /etc/traefik/log/access.log
api:
  dashboard: true
entryPoints:
  http:
    address: :80
  https:
    address: :443
  metrics:
    address: :9091
  postgres:
    address: :5432
http:
  routers:
    dashboard:
      entryPoints:
        - https
      rule: Host(`traefik.jabed.dev`)
      service: api@internal
      tls:
        certResolver: production
        domains:
          - sans: "*.jabed.dev"
      middlewares:
        - basic-auth
  middlewares:
    basic-auth:
      basicAuth:
        usersFile: /etc/traefik/users/users
certificatesResolvers:
  staging:
    acme:
      email: hi@jabed.dev
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
  production:
    acme:
      email: hi@jabed.dev
      storage: /etc/traefik/certs/acme-prod.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
  gen-stage:
    acme:
      email: hi@jabed.dev
      storage: /etc/traefik/certs/acme-gen-stage.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: http
  generic:
    acme:
      email: hi@jabed.dev
      storage: /etc/traefik/certs/acme-generic.json
      httpChallenge:
        entryPoint: http
providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: /etc/traefik
    watch: true
