---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-credentials
  namespace: mongodb
spec:
  encryptedData:
    connectionString.standardSrv: AgCQkt+rt+lwk2zPDJTDLXjAUBSbRDShAK8Bk908AMKKZ82Rq/Gex0Y2LFovz0+egcFWfqfee/ap5Nwboq/M3Xh9+f/rTFjHJx7wp5AREj6jG9I7jLoKSNJ5S77veD4qEQpoA+jnGAnzP8wmK0bpRrk4JTOoQ7kweyJ3HCHnSPXGYPNpeAqA4iRTp+jBRRpn1h1XM6jgmcNp7xaox/Bkkctnk/fVJ8stJcA2Oz8jghJBg6GFuhKxe/uppaOPQuhJ9A3Q6sZf+rqAVQFL2vInmZw3ZKtEgG85+GXnsSome4VVPk5snkt1iONGs1OW/5iGcxBAYve00jjmT1G4E7ehVRmCHZctssmc7qWQNSUFfh5n2Z66NLXWfDll5hXRxDtPggOjSZr87jzEgKWk3exD+cSgFM1JyHR0p281H9DOHdEIFVycc+psAG8MG3mFPNpjzrceL1QoKt8QHnXwXhbyB2IjraBKKdOVoH0cTeI0gZgM7M8SftWYDNcinGBbQKxd0I2g/J/vaOWcqL9VaW7vo6VeZOurip6C3McK3ISjFgp3TCo6Rfk6lQ33xKP9A3Ph3xW1fYxkmjum1GlMUZZCqCFSLXOKPDAWruoeAIFg4jSDmalUvaE0J7qrQU4KmHdKqGnWGMkrE0W9MztiUdujTnnCTuTMll+gvppnT7TbzAhojZ8RVoJFtVxZZp4FtyWpHtIi4n/C7y35QMQ//itTaR+c1/PH1tjysbMDZw5iWipu6zXdYorMe5ZELSNN8l1le+0b0vwEIwDhoo6P91DfoUSnVlmR2Q==
    password: AgBpsykOmBvjWwbdt+Ij9LvKq5dQEtL8Wdpylz1Jp9VVNpR1MCJrzumK3uzMJPTKSvLXTrUm/CGrLCQ+Ck2I8mGddTt527WNmesI214dFpaCZccszo14ZqRtMeO5wnVnPbm91RnrXL/hqfZPo5WvTJ9dlbC1Y26Yso98euUFicy3ofMlzjVnBDP5QexeMRbGOFXZI0BIhXTqVDK9Vsq9xCUscZedSHcJazd5RgwbBx7L6uAbPcsgD1yh5vrDRNATCFNK18C/NG+/v9QfUfZrG0dKTDC9ZQ2O+ALws8qck0yPSka3m7Ts/pNTM7rDvqaHrgftsKT+wXMAiNMGGhYlbsrfefrR9sqCRVstzPv49j5DCSqotHUA62RPWiXGQLGhnDlEF2bvTmNl3kD6zoVR1rsmlmvEXTH96y29tnUxquTe3+sgQr89US/AKmMbqUz8Ti6PxmxfyzYCteXXWC9spjWs3rSv10yCJElAjoUMJ5mo+GamqxyjnPyQ1g4MfgYJ5hheBN2vErWbkBt4fs2hg9Wkx2VrnrXxVejl5D3sQz9QWflCV+ba4nxj0V+k2LgbawWL8Kxpf61Z9J3mh/KfePCbAkU90hFwVhaf9mOd6STLtohzd//u1nbm0rOGPfnMvn9Kj7fsUJ123MkoXHtffc+VdZJ1P0gkaSGVsxeT5b2C2BxcH23INYZ7MSM3hFnoFMebi/0vOHlc1Q==
  template:
    metadata:
      name: mongodb-credentials
      namespace: mongodb
    type: Opaque
