---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-credentials
  namespace: mariadb
spec:
  encryptedData:
    mariadb-password: AgAXUmcyozjvbXISLesQDx6814aVcbBBVqEKv7CUOXrns01yaFJxWeXs8SeZEfBSc+Dn9UVycUomVXAJcWXue14MhV/kTZ3T45KnVvSpWSPhFbcqY/QuaI+aSMz1F4XN4iSUJjOq7tOoRTKQOn0nNwUNqkJ1lRPDoNhQrsSSu4LzlTZgizXeP7L6JoDokPz5cUazdKYDslp6RA0nokz3lvYTVvCeqjlv+nwYpQa8H3fZ3inMFlZZ/XmnZEgUf+L9ofE+3p9zH8h24oqVecw+AfdOvKsRttuOhXspOaFRkXH1HXmvaZPSvSeo+SPZ2uB/eefQfPM/fSxRRH3l/ZyzprswlD3y2C6lHOYr9uyue6G1l0GKWmqMhVMpDdLL0D3xN9djtMmB0iJi5nmrxQ5h2ghzlIZCC1eYc+nBp5KNOLAi6H8bD4ZvbV7i/6iG/MNdm6e5TZOlA05aDjbiZvjm7M/pHeLBZSYvn7mp3eXLvAD0lyl3G9YuQuLLHgBV96TnJfgr1dQP812sw8rK7qMvEyFcSGs1/3a9bcayxSd+oXmQlimc/b/ymLTQvwblS+UXDSGx7GDLfX6vBoQXVwA6SISNgP9l9WpypyxLehloBbF0jrkwt26QhUpWv5qahQNWyECxvQ7GNIvRqqyNB7CBzth4bXYjLo8U1J5hMyCV4SpiEzuk9vaZCZuvDAHyohskDjhPNEgLb9fAng==
    mariadb-root-password: AgCMpYnK3XNJhGa0wHA18TnB7ZYRVH2bhYGW5nCVwwHY5j+3na0nn/8cCvcosA/0A2TlIB42urCVxL4kVlm0KH0CnxIk3Ny/BbDLbt0zVQp6od+hkW5AdodXy6hpyYKEt+nNsqnYgSNn0o9v958R472MZBh8vNcv+4UmIyVpDNIvLZvLVl+a85jFSw7PEebV5EAw01SAXJP8yCaT1H1wNswxuoVyz50bZbyqOsklFvQ6X3DhJjSNaZHQswiY0qsOV6XuVUa2pQlyT1cqgo4oSBItsR6LpiINoKuOK+48T9qBWWGnlbRip3OZZoUdxL3eYUG25DU5zxg6xXYyCJ7APwIw6Xyf7xiP0xgc2RtrULcsXZq5Nl4UQbTg4+UwVoRyc7nXscrBsFcaf8/ELGi0FxWUPzxL526L1KV9AMgvkx/Vp6bQ2lmsDq+EsNeB7nUt9Uj53VpV5b2N0dcKUzT5iv9D9RsPyMGykNu6S/r6b4GrG2XV2Cy3l6iI//mVEbEvCYhQX52Z6MvIsqvqDizBMXH1Tkmxtnae10f0JCfY7iiA5ZtnKxPzFTImNHVM82lo/zcRY1fHpVb9BF0II2gzgfUFg0m1dkjVbjzEkHRgjY2WZbHLnBeY5lV97NkwAAHvnNWHZfQUjUJRsyKjIUgJz7Y3TtS465RBR8pffb+t/CmyShFQBR6M9+eX8AoGcJYk2UJMBbPcuV9ymA==
  template:
    metadata:
      name: mariadb-credentials
      namespace: mariadb
    type: Opaque
