---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: redis
spec:
  encryptedData:
    redis-password: AgC3GtFHjzNmwZ0ge5aWKbLYBVQJeQ6W65hmb9lb1pGq/tgXZyDkKoaNNg5R8EDRmLjg51IrhOmw0D7ojd6wvdlj5zgS1aizDBJyL1DQpz+xZmQcnNhMRMyC9VGsUl7xXDu8d1J0ixaEzuHwEksG7LKBpnYCvG/dJaQIeARWdGVYdR9OzgJO6xCLZq1c+Qzr0Bcti+cxmqqO5QIUkAhZnhLv4cmlW0/R9GJissWK/9xKAeS3z/IeM16qwzJdoteqbwfJYgEkKxRZ7tVARVphsJKhuBX+6bjENL9m7jBV0f+dpq/n1545qrZX10hRD3+jAEyBD3RioMUYMfM41mEleOAOj69t1kguMgzDnGm/HOCVagy/vzzrNIrLyGI+dPwX/RuA/Es8vWoBIhAx47hBdRNZasItOSfmDLYSoSfMTqdRj0sX4OJaIOxQYdhmmkvmsps5F6ZTEIO7q7Qy5KXtR4NDWmUrabKA7ATh+8TZqTJiSVN514r+FziQf1W+2C//AQUUtu2xYAwv8RPUMvOplZRutw2WdxfaWUV+DT63in0oSXV7NwjOClqaDoG6jAMH7NlLESQ7le0IZA6zTFhQiiuH7nAgvOyB26Uu4U8u38EyHC/hdUuEk2NT2wF+vUetKwZDG1KiLFPL15eHNPYCo8Bylg14V+kI/8U94dThu0swMIzbp2zWPr3D1bUyyqkGPBct0rVoM+KKrA==
    redis-username: AgDDlFqypKkV/RSLucZMWPItq4AOnr0gPlZl6ln5z0Vmycs/UUGluLqbdMCM/EGHjC7uSp1mUmu5gcMH2RvzM5X9O5ucli2TdjTGsKjFmyUGksdvqK5JZAmIH6aX789+POGFTzDl8rnwRzfKxRKTGkN7kh3RKEcpsnYzOPmBzD2FRVAAn6oCRwn/PUIHmpkOK/JvybiHsJ/oUe60xT8bhs4b159A/+jJ9LjFejHT3WNNTeMZEoCWrIYF+oQv3K3v5SepFBgl7h/BfFMJkKTdpcqWJAO86dOGqu2FqsKz1pDVdfA6o4wN4pU8+V70xcmeH9LrJxKmFAiMaWB37iAKR1Z8NGoEGlj67cuLgKFmxus7VknkfFSmt2G2kIlFRJ9yteawruXQnl9x2FGcmNY+k2kviAP/WKAesRL6UQjWUJG6zDNFxBjQjXrhlArPtwe3+2QnP+vQyOVYGpiJF3sZjT9eIP7pbaTjwiXPZdzzjqtdobl5913FkHZjleVC70mRypS1ipvLkJVDqgY31mfRTPwf051jb7BBAId9M81I3chRXRI413INOQszvmWAHBLU93YHfbDLBVt9sEjEEHZUS7P0AayPm2juxZ2E7578WSpiwJqx35ZSq4sNtJGmwk2LIUXpuYOQiwOhsmK2+FvczcDgzn8T9klXGEzzov2s+l48APgCclWP0uyoauKfKXPjyQyobr06iw==
  template:
    metadata:
      name: redis-credentials
      namespace: redis
    type: Opaque
