---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secrets
  namespace: n8n
spec:
  encryptedData:
    N8N_ENCRYPTION_KEY: AgB9S9Bt134C/J9xbytzE8j/ubfRIZCSpVaL8xSBg/9DnO+sjIfKPrG1DLUF4ymoMaStcWbi68UnIMzbg4NmYdP1ykUnhjkmWzICgiyTh7vcOYs5T44DiyPnrvT38rF/V+VPE9AzQhCXTRdWMBetHsiu6DibjFjHy1S/cmb8mVIsSwt3oNfoHf2Drpz2E9euak6aCNV6mFs2u0kUoWWop7e4J7HFR/oZxFxBga4CR2Kiym6+lM5wihMfQpMOuJVoW5+oS3smNF76Wp/QhM8OkFzRiIrhF8F8jxs2RavVVaVtTEM7lQGNEag3JMVHras/3M0dJeivA9n2BaRjU32clmABBw5TekXVQ5WajM0ufBn3t3Hz5BKmtbabXWBImhZNcNKkQmPYoCPqaXEt7uXFeKkVDXHT19hBFGL1oVjUnrEg1m7a0H4nj2ioQi7HdI1kdt0g5lkwYwxOsTF0ed/dM4CcIliV8f7LawVhZYZlE8iGk5FdbkvN40AGys4+JuU3vEfGbl5I1+sGDB9DXdk1rWxIn8Kj977v1PDAI+X4yrvAXmuMuS0VrAmua5kypZLU8evAnb13y9lrViBFzI7vMmyT7DUZg6nB2Popc15NzUr3GiYDqlhRGsoiWfuz9mApdiqolYBRPUs6tmLc2QiAH6g17OHmSiHFMX/oHfi0agudsI4mydEJy2vXDzfuvgo/btxsdZ4dqqPHkpa/1oLjlPBPp51oNlq3cNJvZV1XQwaTtc7O7CJ3cQocgExsE7JZ2Q5+psvp4JvbC0FsMH+RbC5n
  template:
    metadata:
      name: n8n-secrets
      namespace: n8n
    type: Opaque
